- type: tf
  topic: /tf
  folder: transforms
  args:
    base_frame: odom
    target_frames:
      - base
    euler: true
    sample_rate: 100.0

- type: tf
  topic: /tf
  folder: transforms_static
  args:
    base_frame: base
    target_frames:
      - pylon_camera
      - lidar
      - wide_angle_camera_rear_camera_parent
      - wide_angle_camera_front_camera_parent
    euler: true
    sample_rate: 0.1

- type: anymal_state
  topic: /legged_odometry/anymal_state
  folder: state

- type: anymal_actuators
  topic: /anymal_low_level_controller/actuator_readings
  folder: actuators

- type: imu
  topic: /sensors/imu
  folder: imu

- type: basic
  topic: /theodolite_data
  folder: theodolite

- type: image
  topic: /pylon_camera_node/image_raw
  folder: front_center_camera
  args:
    extension: png
    rectify: true
    video: true
    debayer: true

- type: image
  topic: /wide_angle_camera_rear/image_mono/compressed
  folder: wide_angle_rear
  args:
    extension: png
    rectify: true
    video: true

- type: image
  topic: /wide_angle_camera_front/image_mono/compressed
  folder: wide_angle_front
  args:
    extension: png
    rectify: true
    video: true

- type: point_cloud
  topic: /lidar/point_cloud
  folder: lidar
