- type: image
  topic: /boxi/alphasense/front_center/image_raw/compressed
  folder: front_center_camera
  args:
    extension: png
    rectify: true
    video: true

- type: tf
  topic: /tf
  folder: transforms
  args:
    base_frame: dlio_map
    target_frames:
      - LF_FOOT
      - RF_FOOT
      - LH_FOOT
      - RH_FOOT
      - base
      - alphasense_front_center
    euler: true
    sample_rate: 100.0

- type: anymal_state
  topic: /anymal/state_estimator/anymal_state
  folder: state

- type: anymal_actuators
  topic: /anymal/actuator_readings
  folder: actuators
